### PR TITLE
windows build fix

### PR DESCRIPTION
**Pull request by dcarlier-afilias**

### CODE REVIEW

**Comment by sneves** [comment]
Thanks!

**Comment by BurningEnlightenment** [comment]
if I may ask, what exactly was broken? 🤨

**Comment by devnexen** [comment]
Linkage issue since, if I understood correctly, it s implemented in a header (Python uses blake2 with their windows travis build this is how I spotted the issue).

**Comment by sneves** [comment]
`SecureZeroRandom` was potentially undefined without `windows.h`.

**Pull request merged**
